
eureka:
  client:
    service-url:
      defaultZone: http://39.108.189.144:6868/eureka/
spring:
  rabbitmq:
    host: 39.108.189.144
    username: lypee
    password: lypee
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Ly123456
    url: jdbc:mysql://39.108.189.144:3306/tensquare_friend?characterEncoding=utf-8
  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: "lypee"
server:
  port: 9010
