server:
  port: 9005
spring:
  rabbitmq:
    host: 39.108.189.144
    username: lypee
    password: lypee
  application:
    name: tensquare-gathering
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.189.144:3306/tensquare_gathering?chaactorEncoding=UTF8
    username: root
    password: Ly123456
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://39.108.189.144:6868/eureka/
