server:
  port: 9011
spring:
  rabbitmq:
    host: 39.108.189.144
    username: lypee
    password: lypee
  application:
    name: tensquare-manage
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
zuul:
  routes:
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
    tensquare-admin:
      path: /admin/**
      serviceId: tensquare-user
    tensquare-friend:
      path: /friend/**
      serviceId: tensquare-friend
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-enterprise:
      path: /enterprise/**
      serviceId: tensquare-recruit
    tensquare-recruit:
      path: /recruit/**
      serviceId: tensquare-recruit
    tensquare-article:
      path: /article/**
      serviceId: tensquare-article
    tensquare-spit:
      path: /spit/**
      serviceId: tensquare-spit
jwt:
  config:
    key: "lypee"
