server:
  port: 9003
spring:
  rabbitmq:
    host: 39.108.189.144
    username: lypee
    password: lypee
  application:
    name: tensquare-qa #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.189.144:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: Ly123456
  jpa:
    database: MySQL
    show-sql: true
jwt:
  config:
    key: "lypee"
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 10000
