server:
  port: 9007
spring:
  rabbitmq:
    host: 39.108.189.144
    username: lypee
    password: lypee
  application:
    name: tensquare-search
  data:
    elasticsearch:
      cluster-nodes: 39.108.189.144:9300
      cluster-name: elasticsearch
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
