server:
  port: 9009
spring:
  rabbitmq:
    host: 39.108.189.144
    username: lypee
    password: lypee
  application:
    name: tensquare-sms
aliyun:
  sms:
    accessKeyId: LTAILNrhJAYrPaQe
    accessKeySecret: q7fOlR8liJcFAFBs5SCsnWCzbKhqKK
    template_code: SMS_166372744
    sign_name: 十次方社交网站
eureka:
  client:
    service-url:
      defaultZone: http://39.108.189.144:6868/eureka/
